manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    - name: eloback
      url-base: https://github.com/eloback
  projects:
    - name: zmk
      remote: eloback
      revision: adv360-z3.5
      import: app/west.yml
    - name: zmk-helpers
      remote: urob
      revision: v2
  self:
    path: config
